services:
  p115-strm-lite:
    image: ghcr.io/chn-wxg/p115-strm-lite:latest
    container_name: p115-strm-lite
    restart: unless-stopped
    ports:
      - "18080:8080"
    volumes:
      - ./config:/config
      - /vol1/1000/media:/media
    environment:
      - TZ=Asia/Shanghai
      - P115_STRM_CONFIG=/config/config.yaml
